export interface ClassSample {
  id: string;
  type: 'image' | 'video';
  dataUrl: string; // Base64 image or video
  timestamp: number;
}

export interface MachineClass {
  id: string;
  name: string;
  samples: ClassSample[];
  description?: string; // Generated by Gemini during "training"
}

export enum AppState {
  LANDING = 'LANDING',
  WORKBENCH = 'WORKBENCH'
}

export enum TrainingState {
  IDLE = 'IDLE',
  TRAINING = 'TRAINING',
  READY = 'READY'
}
